# ============================================================
# MIMIC PATIENT ANALYTICS
# SHARED VISUAL THEME
# ============================================================

import streamlit as st


# ============================================================
# COLOR TOKENS
# ============================================================

COLORS = {
    # Dashboard accents
    "teal": "#2DD4BF",
    "sky": "#38BDF8",
    "violet": "#8B7FD6",
    "amber": "#F5A623",
    "rose": "#FB7185",

    # Dark KPI cards
    "card_bg": "#111C2E",
    "card_border": "rgba(148, 197, 213, 0.16)",

    # Light theme
    "light_text": "#0F172A",
    "light_muted": "#64748B",
    "light_border": "#E2E8F0",

    # Dark theme
    "dark_text": "#E7EFF6",
    "dark_muted": "#8CA0B3",
    "dark_border": "rgba(148, 197, 213, 0.16)",
}


ACCENT_CYCLE = [
    COLORS["teal"],
    COLORS["sky"],
    COLORS["violet"],
    COLORS["amber"],
    COLORS["rose"],
]


# ============================================================
# GLOBAL CSS
# ============================================================

_CUSTOM_CSS = f"""
<style>

@import url(
    'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500;600;700'
    '&family=IBM+Plex+Sans:wght@400;500;600;700'
    '&display=swap'
);


/* ==========================================================
   GLOBAL TYPOGRAPHY
   ========================================================== */

/*
   Streamlit itself controls the page's foreground/background
   through CSS variables. We only control typography here.

   This prevents our custom theme from fighting Streamlit's
   light/dark theme.
*/

html,
body,
[class*="st-"],
[data-testid="stAppViewContainer"],
[data-testid="stSidebar"],
[data-testid="stMarkdownContainer"],
[data-testid="stText"] {{
    font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont,
                 'Segoe UI', sans-serif !important;
}}


/* Headings generated by native Streamlit */
h1,
h2,
h3,
h4,
h5,
h6 {{
    font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont,
                 'Segoe UI', sans-serif !important;
}}


/* Native Streamlit text */
p,
label,
span,
div {{
    font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont,
                 'Segoe UI', sans-serif;
}}


/* ==========================================================
   HERO
   ========================================================== */

.mimic-eyebrow {{
    font-family: 'IBM Plex Mono', monospace !important;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.18em;
    text-transform: uppercase;

    color: {COLORS["teal"]} !important;

    margin-bottom: 0.6rem;
}}


.mimic-hero-title {{
    font-family: 'IBM Plex Sans', sans-serif !important;
    font-weight: 700;
    font-size: 2.6rem;
    line-height: 1.15;

    /*
       IMPORTANT:
       Use Streamlit's own text variable instead of hard-coding
       a light/dark color.
    */
    color: var(--text-color) !important;

    margin: 0 0 0.6rem 0;
}}


.mimic-hero-subtitle {{
    font-family: 'IBM Plex Sans', sans-serif !important;
    font-size: 1.05rem;
    font-weight: 400;
    line-height: 1.6;

    color: var(--secondary-text-color, #64748B) !important;

    max-width: 46rem;
    margin: 0;
}}


/* ==========================================================
   KPI METRIC CARDS
   ========================================================== */

.mimic-metric-card {{
    background: {COLORS["card_bg"]};

    border: 1px solid {COLORS["card_border"]};
    border-left: 3px solid var(--mimic-accent, {COLORS["teal"]});

    border-radius: 12px;

    padding: 1.1rem 1.25rem;

    height: 100%;
    box-sizing: border-box;

    transition:
        transform 0.15s ease,
        box-shadow 0.15s ease;
}}


.mimic-metric-card:hover {{
    transform: translateY(-3px);

    box-shadow:
        0 10px 26px rgba(0, 0, 0, 0.20);
}}


.mimic-metric-icon {{
    font-size: 1.3rem;
    line-height: 1;

    opacity: 0.95;

    margin-bottom: 0.65rem;
}}


.mimic-metric-value {{
    font-family: 'IBM Plex Mono', monospace !important;
    font-weight: 600;

    font-size: 1.65rem;
    line-height: 1.2;

    /*
       KPI cards are ALWAYS dark.
       Therefore their values should ALWAYS be light.
    */
    color: {COLORS["dark_text"]} !important;

    margin: 0;
}}


.mimic-metric-label {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    font-size: 0.74rem;
    font-weight: 600;

    letter-spacing: 0.06em;
    text-transform: uppercase;

    color: {COLORS["dark_muted"]} !important;

    margin-top: 0.3rem;
}}


/* ==========================================================
   SECTION TITLES
   ========================================================== */

.mimic-section-title {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    font-weight: 600;
    font-size: 1.1rem;
    line-height: 1.3;

    /*
       Native Streamlit theme decides whether this is
       light or dark.
    */
    color: var(--text-color) !important;

    margin: 0 0 0.9rem 0;
}}


/* ==========================================================
   DASHBOARD NAVIGATION CARDS
   ========================================================== */

.mimic-nav-icon {{
    font-size: 1.6rem;
    line-height: 1;

    margin-bottom: 0.2rem;
}}


.mimic-nav-title {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    font-weight: 600;
    font-size: 1.02rem;
    line-height: 1.3;

    color: var(--text-color) !important;

    margin: 0.4rem 0 0.15rem 0;
}}


.mimic-nav-desc {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    font-size: 0.85rem;
    font-weight: 400;
    line-height: 1.45;

    color: var(--secondary-text-color, #64748B) !important;

    margin-bottom: 0.6rem;
}}


/* ==========================================================
   NAVIGATION CARD "OPEN" LINK
   ========================================================== */

/*
   st.page_link() is a native Streamlit component.
   Force its typography to match the rest of the dashboard.
*/

[data-testid="stPageLink-NavLink"],
[data-testid="stPageLink-NavLink"] span,
[data-testid="stPageLink-NavLink"] p {{
    font-family: 'IBM Plex Sans', sans-serif !important;
    font-weight: 500 !important;
}}


/* ==========================================================
   SIDEBAR
   ========================================================== */

.mimic-sidebar-brand {{
    display: flex;
    align-items: center;

    gap: 0.5rem;

    padding: 0.2rem 0 1rem 0;
    margin-bottom: 0.4rem;

    border-bottom: 1px solid var(
        --secondary-background-color,
        #E2E8F0
    );
}}


.mimic-sidebar-brand-icon {{
    font-size: 1.3rem;
    line-height: 1;
}}


.mimic-sidebar-brand-text {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    font-weight: 700;
    font-size: 1.02rem;

    color: var(--text-color) !important;

    letter-spacing: 0.01em;
}}


.mimic-sidebar-section {{
    font-family: 'IBM Plex Mono', monospace !important;

    font-size: 0.68rem;
    font-weight: 600;

    letter-spacing: 0.14em;
    text-transform: uppercase;

    color: var(--secondary-text-color, #64748B) !important;

    margin: 1.1rem 0 0.3rem 0.1rem;
}}


.mimic-sidebar-footer {{
    font-family: 'IBM Plex Mono', monospace !important;

    font-size: 0.70rem;

    color: var(--secondary-text-color, #64748B) !important;

    margin-top: 1.4rem;

    padding-top: 0.9rem;

    border-top: 1px solid var(
        --secondary-background-color,
        #E2E8F0
    );
}}


/* Sidebar page links */

section[data-testid="stSidebar"]
[data-testid="stPageLink-NavLink"] {{
    border-radius: 8px;

    transition:
        background-color 0.15s ease,
        color 0.15s ease;
}}


section[data-testid="stSidebar"]
[data-testid="stPageLink-NavLink"]:hover {{
    background-color: rgba(45, 212, 191, 0.08);
}}


/* ==========================================================
   NATIVE STREAMLIT DIVIDERS
   ========================================================== */

hr {{
    border-color: var(
        --secondary-background-color,
        #E2E8F0
    ) !important;
}}


/* ==========================================================
   NATIVE STREAMLIT CAPTION
   ========================================================== */

[data-testid="stCaptionContainer"] {{
    font-family: 'IBM Plex Sans', sans-serif !important;

    color: var(
        --secondary-text-color,
        #64748B
    ) !important;
}}


/* ==========================================================
   REDUCE MOTION
   ========================================================== */

@media (prefers-reduced-motion: reduce) {{

    .mimic-metric-card {{
        transition: none;
    }}

}}

</style>
"""


# ============================================================
# THEME INJECTION
# ============================================================

def inject_theme():
    """
    Inject the shared MIMIC Analytics visual theme.

    This function deliberately does NOT attempt to detect
    Streamlit's light/dark theme with JavaScript.

    Streamlit already exposes theme colors through CSS variables
    such as --text-color and --secondary-text-color. Using those
    variables keeps custom components synchronized with the
    native Streamlit theme.
    """

    st.markdown(
        _CUSTOM_CSS,
        unsafe_allow_html=True
    )


# ============================================================
# ECG WAVEFORM
# ============================================================

def ecg_divider(accent=None, cycles=10, height=34):
    """
    Render the ECG waveform used as the dashboard's signature
    visual divider.
    """

    accent = accent or COLORS["teal"]

    cycle_width = 160
    baseline = height / 2

    segment_template = (
        "L{x0},{b} "
        "L{x1},{b} "
        "L{x2},{small_dip} "
        "L{x3},{big_peak} "
        "L{x4},{deep_trough} "
        "L{x5},{b} "
        "L{x6},{small_bump} "
        "L{x7},{b} "
    )

    path_parts = [
        f"M0,{baseline}"
    ]

    peak_amplitude = baseline * 0.85
    trough_amplitude = (height - baseline) * 0.7
    small_dip_amplitude = (height - baseline) * 0.35
    small_bump_amplitude = baseline * 0.3

    for cycle in range(cycles):

        x0 = cycle * cycle_width

        path_parts.append(
            segment_template.format(
                x0=x0 + 0,
                x1=x0 + 34,
                x2=x0 + 40,
                x3=x0 + 48,
                x4=x0 + 56,
                x5=x0 + 62,
                x6=x0 + 70,
                x7=x0 + 160,
                b=baseline,
                small_dip=baseline + small_dip_amplitude,
                big_peak=baseline - peak_amplitude,
                deep_trough=baseline + trough_amplitude,
                small_bump=baseline - small_bump_amplitude,
            )
        )

    path_d = " ".join(path_parts)

    total_width = cycles * cycle_width

    svg = f"""
    <div
        style="
            width:100%;
            overflow:hidden;
            margin:0.4rem 0 1.4rem 0;
        "
    >
        <svg
            viewBox="0 0 {total_width} {height}"
            preserveAspectRatio="none"
            width="100%"
            height="{height}"
        >
            <path
                d="{path_d}"
                fill="none"
                stroke="{accent}"
                stroke-width="1.6"
                stroke-linejoin="round"
                stroke-linecap="round"
                opacity="0.85"
            />
        </svg>
    </div>
    """

    return svg


# ============================================================
# HERO HEADER
# ============================================================

def render_hero(
    eyebrow,
    title,
    subtitle,
    accent=None
):
    """
    Render the page hero:

        eyebrow
        title
        subtitle
        ECG divider
    """

    accent = accent or COLORS["teal"]

    st.markdown(
        f"""
        <div class="mimic-eyebrow">
            {eyebrow}
        </div>

        <div class="mimic-hero-title">
            {title}
        </div>

        <p class="mimic-hero-subtitle">
            {subtitle}
        </p>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        ecg_divider(accent=accent),
        unsafe_allow_html=True
    )


# ============================================================
# METRIC CARD
# ============================================================

def render_metric_card(
    icon,
    value,
    label,
    accent=None
):
    """
    Render one KPI card.

    Example:

        with col:
            render_metric_card(
                "🏨",
                "275",
                "Admissions",
                accent="#38BDF8"
            )
    """

    accent = accent or COLORS["teal"]

    st.markdown(
        f"""
        <div
            class="mimic-metric-card"
            style="--mimic-accent: {accent};"
        >

            <div class="mimic-metric-icon">
                {icon}
            </div>

            <div class="mimic-metric-value">
                {value}
            </div>

            <div class="mimic-metric-label">
                {label}
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )


# ============================================================
# METRIC ROW
# ============================================================

def metric_row(columns, cards):
    """
    Render a row of KPI metric cards.

    Parameters
    ----------
    columns:
        Streamlit columns returned by st.columns()

    cards:
        List of dictionaries containing:

            icon
            value
            label
            accent (optional)
    """

    for col, card in zip(columns, cards):

        with col:

            render_metric_card(
                icon=card["icon"],
                value=card["value"],
                label=card["label"],
                accent=card.get("accent")
            )
